# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/holiday/setup-makefiles.sh
PRODUCT_COPY_FILES += \
    device/htc/holiday/prebuilt/lib/libaudioalsa.so:obj/lib/libaudioalsa.so \
    device/htc/holiday/prebuilt/lib/libacdbmapper.so:obj/lib/libacdbmapper.so \
    device/htc/holiday/prebuilt/lib/libacdbloader.so:obj/lib/libacdbloader.so \
    device/htc/holiday/prebuilt/lib/libaudioalsa.so.so:obj/lib/libaudioalsa.so \
    device/htc/holiday/prebuilt/lib/liboncrpc.so:obj/lib/liboncrpc.so \
    device/htc/holiday/prebuilt/lib/libnv.so:obj/lib/libnv.so \
    device/htc/holiday/prebuilt/lib/libv8.so:obj/lib/libv8.so \
    device/htc/holiday/prebuilt/lib/libqc-opt.so:obj/lib/libqc-opt.so \
    device/htc/holiday/prebuilt/lib/hw/camera.vendor.msm8660.so:obj/lib/hw/camera.vendor.msm8660.so

PRODUCT_COPY_FILES += \
    device/htc/holiday/prebuilt/etc/vpimg:system/etc/vpimg \
    device/htc/holiday/prebuilt/bin/awb_camera:system/bin/awb_camera \
    device/htc/holiday/prebuilt/bin/bma150_usr:system/bin/bma150_usr \
    device/htc/holiday/prebuilt/bin/charging:system/bin/charging \
    device/htc/holiday/prebuilt/bin/dmagent:system/bin/dmagent \
    device/htc/holiday/prebuilt/bin/htcbatt:system/bin/htcbatt \
    device/htc/holiday/prebuilt/bin/ip:system/bin/ip \
    device/htc/holiday/prebuilt/bin/ks:system/bin/ks \
    device/htc/holiday/prebuilt/bin/mm-abl-daemon:system/bin/mm-abl-daemon \
    device/htc/holiday/prebuilt/bin/mpdecision:system/bin/mpdecision \
    device/htc/holiday/prebuilt/bin/netmgrd:system/bin/netmgrd \
    device/htc/holiday/prebuilt/bin/netsharing:system/bin/netsharing \
    device/htc/holiday/prebuilt/bin/qcks:system/bin/qcks \
    device/htc/holiday/prebuilt/bin/qmiproxy:system/bin/qmiproxy \
    device/htc/holiday/prebuilt/bin/qmuxd:system/bin/qmuxd \
    device/htc/holiday/prebuilt/bin/rmt_storage:system/bin/rmt_storage \
    device/htc/holiday/prebuilt/bin/thermald:system/bin/thermald \
    device/htc/holiday/prebuilt/bin/wireless_modem:system/bin/wireless_modem \
    device/htc/holiday/prebuilt/bin/zchgd:system/bin/zchgd \
    device/htc/holiday/prebuilt/lib/libhtc_acoustic.so:system/lib/libhtc_acoustic.so \
    device/htc/holiday/prebuilt/lib/libaudioalsa.so:system/lib/libaudioalsa.so \
    device/htc/holiday/prebuilt/lib/libaudcal.so:system/lib/libaudcal.so \
    device/htc/holiday/prebuilt/lib/libacdbmapper.so:system/lib/libacdbmapper.so \
    device/htc/holiday/prebuilt/lib/libacdbloader.so:system/lib/libacdbloader.so \
    device/htc/holiday/prebuilt/lib/hw/camera.vendor.msm8660.so:system/lib/hw/camera.vendor.msm8660.so \
    device/htc/holiday/prebuilt/lib/libcamerapp.so:system/lib/libcamerapp.so \
    device/htc/holiday/prebuilt/lib/libcameraface.so:system/lib/libcameraface.so \
    device/htc/holiday/prebuilt/lib/libposteffect.so:system/lib/libposteffect.so \
    device/htc/holiday/prebuilt/lib/libOlaEngine.so:system/lib/libOlaEngine.so \
    device/htc/holiday/prebuilt/lib/liboemcamera.so:system/lib/liboemcamera.so \
    device/htc/holiday/prebuilt/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    device/htc/holiday/prebuilt/lib/libmmipl.so:system/lib/libmmipl.so \
    device/htc/holiday/prebuilt/lib/libgemini.so:system/lib/libgemini.so \
    device/htc/holiday/prebuilt/lib/libidl.so:system/lib/libidl.so \
    device/htc/holiday/prebuilt/lib/libchromatix_s5k3h2yx_zsl.so:system/lib/libchromatix_s5k3h2yx_zsl.so \
    device/htc/holiday/prebuilt/lib/libchromatix_s5k3h2yx_preview.so:system/lib/libchromatix_s5k3h2yx_preview.so \
    device/htc/holiday/prebuilt/lib/libchromatix_s5k3h2yx_hfr.so:system/lib/libchromatix_s5k3h2yx_hfr.so \
    device/htc/holiday/prebuilt/lib/libchromatix_s5k3h2yx_default_video.so:system/lib/libchromatix_s5k3h2yx_default_video.so \
    device/htc/holiday/prebuilt/lib/libchromatix_s5k3h1gx_zsl.so:system/lib/libchromatix_s5k3h1gx_zsl.so \
    device/htc/holiday/prebuilt/lib/libchromatix_s5k3h1gx_preview.so:system/lib/libchromatix_s5k3h1gx_preview.so \
    device/htc/holiday/prebuilt/lib/libchromatix_s5k3h1gx_zsl.so:system/lib/libchromatix_s5k3h1gx_zsl.so \
    device/htc/holiday/prebuilt/lib/libchromatix_s5k3h1gx_hfr.so:system/lib/libchromatix_s5k3h1gx_hfr.so \
    device/htc/holiday/prebuilt/lib/libchromatix_s5k3h1gx_default_video.so:system/lib/libchromatix_s5k3h1gx_default_video.so \
    device/htc/holiday/prebuilt/lib/libchromatix_ov8830_zsl.so:system/lib/libchromatix_ov8830_zsl.so \
    device/htc/holiday/prebuilt/lib/libchromatix_ov8830_preview.so:system/lib/libchromatix_ov8830_preview.so \
    device/htc/holiday/prebuilt/lib/libchromatix_ov8830_hfr.so:system/lib/libchromatix_ov8830_hfr.so \
    device/htc/holiday/prebuilt/lib/libchromatix_ov8830_default_video.so:system/lib/libchromatix_ov8830_default_video.so \
    device/htc/holiday/prebuilt/lib/libchromatix_mt9d015_preview.so:system/lib/libchromatix_mt9d015_preview.so \
    device/htc/holiday/prebuilt/lib/libchromatix_mt9d015_default_zsl.so:system/lib/libchromatix_mt9d015_default_zsl.so \
    device/htc/holiday/prebuilt/lib/libchromatix_mt9d015_default_video.so:system/lib/libchromatix_mt9d015_default_video.so \
    device/htc/holiday/prebuilt/lib/libchromatix_imx105_zsl.so:system/lib/libchromatix_imx105_zsl.so \
    device/htc/holiday/prebuilt/lib/libchromatix_imx105_preview.so:system/lib/libchromatix_imx105_preview.so \
    device/htc/holiday/prebuilt/lib/libchromatix_imx105_default_video.so:system/lib/libchromatix_imx105_default_video.so \
    device/htc/holiday/prebuilt/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
    device/htc/holiday/prebuilt/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    device/htc/holiday/prebuilt/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    device/htc/holiday/prebuilt/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    device/htc/holiday/prebuilt/lib/egl/libplayback_adreno200.so:system/lib/egl/libplayback_adreno200.so \
    device/htc/holiday/prebuilt/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
    device/htc/holiday/prebuilt/lib/libsc-a2xx.so:system/lib/libsc-a2xx.so \
    device/htc/holiday/prebuilt/lib/libllvm-arm.so:/system/lib/libllvm-arm.so \
    device/htc/holiday/prebuilt/lib/libOpenVG.so:system/lib/libOpenVG.so \
    device/htc/holiday/prebuilt/lib/libOpenCL.so:system/lib/libOpenVG.so \
    device/htc/holiday/prebuilt/lib/libgsl.so:system/lib/libgsl.so \
    device/htc/holiday/prebuilt/lib/libC2D2.so:system/lib/libC2D2.so \
    device/htc/holiday/prebuilt/lib/libc2d2_z180.so:system/lib/libc2d2_z180.so \
    device/htc/holiday/prebuilt/lib/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
    device/htc/holiday/prebuilt/lib/liboncrpc.so:system/lib/liboncrpc.so \
    device/htc/holiday/prebuilt/lib/libdsm.so:system/lib/libdsm.so \
    device/htc/holiday/prebuilt/lib/libdiag.so:system/lib/libdiag.so \
    device/htc/holiday/prebuilt/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
    device/htc/holiday/prebuilt/lib/libdsutils.so:system/lib/libdsutils.so \
    device/htc/holiday/prebuilt/lib/libnetmgr.so:system/lib/libnetmgr.so \
    device/htc/holiday/prebuilt/lib/libnv.so:system/lib/libnv.so \
    device/htc/holiday/prebuilt/lib/libpbmlib.so:system/lib/libpbmlib.so \
    device/htc/holiday/prebuilt/lib/libqmiservices.so:system/lib/libqmiservices.so \
    device/htc/holiday/prebuilt/lib/libqmi.so:system/lib/libqmi.so \
    device/htc/holiday/prebuilt/lib/libqdp.so:system/lib/libqdp.so \
    device/htc/holiday/prebuilt/lib/libqc-opt.so:system/lib/libqc-opt.so \
    device/htc/holiday/prebuilt/lib/libqueue.so:system/lib/libqueue.so \
    device/htc/holiday/prebuilt/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
    device/htc/holiday/prebuilt/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    device/htc/holiday/prebuilt/lib/hw/sensors.holiday.so:system/lib/hw/sensors.holiday.so \
    device/htc/holiday/prebuilt/lib/libmpl_jni.so:system/lib/libmpl_jni.so \
    device/htc/holiday/prebuilt/lib/libmpl.so:system/lib/libmpl.so \
    device/htc/holiday/prebuilt/lib/libmlplatform.so:system/lib/libmlplatform.so \
    device/htc/holiday/prebuilt/lib/libmllite.so:system/lib/libmllite.so \
    device/htc/holiday/prebuilt/lib/libril.so:system/lib/libril.so \
    device/htc/holiday/prebuilt/lib/libv8.so:system/lib/libv8.so \
    device/htc/holiday/prebuilt/app/Camera2.apk:system/app/Camera2.apk \
    device/htc/holiday/prebuilt/app/Camera2.apk:system/priv-app/Camera2.apk
